[package]
name = "generic-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.149"
borsh = { version = "1.6.0", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
wincode = { version = "0.4.4", features = ["derive"] }
